# Generated by Django 4.1.4 on 2022-12-28 00:05

from django.db import migrations, models

import tracker.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField()),
                ("comment", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=models.SET(tracker.models.get_empty_tag),
                        related_name="entries_in_category",
                        to="tracker.tag",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_entries", to="tracker.tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-date"],
            },
        ),
    ]
