name: Deploy
on: push
jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv
      - name: Install Python dependencies
        run: pipenv sync --categories=linters
      - name: Install Node dependencies
        run: npm ci
      - name: Run linters
        run: pipenv run ./lint.sh
